// packages/navi-app/src/lib/components/WorkingIndicator.svelte
<script lang="ts">
  import DoodleThinking from "./DoodleThinking.svelte";

  type Variant = "pulse" | "spin" | "dots" | "doodle";
  type Size = "xs" | "sm" | "md" | "lg";
  type Color = "gray" | "blue" | "indigo" | "purple" | "green" | "orange" | "red";

  interface Props {
    variant?: Variant;
    size?: Size;
    color?: Color;
    label?: string;
    class?: string;
  }

  let { variant = "spin", size = "sm", color = "gray", label, class: className = "" }: Props = $props();

  // Map WorkingIndicator sizes to DoodleThinking sizes
  const doodleSizeMap: Record<Size, "sm" | "md" | "lg"> = {
    xs: "sm",
    sm: "sm",
    md: "md",
    lg: "lg",
  };

  const sizeMap: Record<Size, string> = {
    xs: "w-1.5 h-1.5",
    sm: "w-2 h-2",
    md: "w-3 h-3",
    lg: "w-4 h-4",
  };

  const spinSizeMap: Record<Size, string> = {
    xs: "w-2 h-2 border",
    sm: "w-3 h-3 border-2",
    md: "w-4 h-4 border-2",
    lg: "w-5 h-5 border-2",
  };

  const colorMap: Record<Color, { bg: string; border: string; borderTop: string; text: string }> = {
    gray: { bg: "bg-gray-400", border: "border-gray-300", borderTop: "border-t-gray-700", text: "text-gray-500" },
    blue: { bg: "bg-blue-500", border: "border-blue-300", borderTop: "border-t-blue-600", text: "text-blue-500" },
    indigo: { bg: "bg-indigo-500", border: "border-indigo-300", borderTop: "border-t-indigo-600", text: "text-indigo-500" },
    purple: { bg: "bg-purple-500", border: "border-purple-300", borderTop: "border-t-purple-600", text: "text-purple-500" },
    green: { bg: "bg-green-500", border: "border-green-300", borderTop: "border-t-green-600", text: "text-green-500" },
    orange: { bg: "bg-orange-500", border: "border-orange-300", borderTop: "border-t-orange-600", text: "text-orange-500" },
    red: { bg: "bg-red-500", border: "border-red-300", borderTop: "border-t-red-600", text: "text-red-500" },
  };

  const colors = $derived(colorMap[color]);
</script>

{#if variant === "pulse"}
  <span class="flex items-center gap-1 {className}">
    <span class="{sizeMap[size]} {colors.bg} rounded-full animate-pulse"></span>
    {#if label}
      <span class="text-xs {colors.text}">{label}</span>
    {/if}
  </span>
{:else if variant === "spin"}
  <span class="flex items-center gap-2 {className}">
    <span class="{spinSizeMap[size]} {colors.border} {colors.borderTop} rounded-full animate-spin"></span>
    {#if label}
      <span class="text-xs {colors.text}">{label}</span>
    {/if}
  </span>
{:else if variant === "dots"}
  <span class="flex items-center gap-2 {className}">
    <span class="flex gap-0.5">
      <span class="{sizeMap[size]} {colors.bg} rounded-full animate-bounce" style="animation-delay: 0ms"></span>
      <span class="{sizeMap[size]} {colors.bg} rounded-full animate-bounce" style="animation-delay: 150ms"></span>
      <span class="{sizeMap[size]} {colors.bg} rounded-full animate-bounce" style="animation-delay: 300ms"></span>
    </span>
    {#if label}
      <span class="text-xs {colors.text}">{label}</span>
    {/if}
  </span>
{:else if variant === "doodle"}
  <DoodleThinking size={doodleSizeMap[size]} {label} class={className} />
{/if}

// packages/navi-remix/app/components/chat/WorkingIndicator.tsx
interface WorkingIndicatorProps {
  label?: string;
  variant?: "dots" | "spinner" | "pulse";
  size?: "xs" | "sm" | "md" | "lg";
  color?: "gray" | "blue" | "indigo" | "purple" | "green" | "orange" | "red";
}

export function WorkingIndicator({
  label,
  variant = "dots",
  size = "xs",
  color = "gray",
}: WorkingIndicatorProps) {
  const colorClasses: Record<string, string> = {
    gray: "bg-gray-400",
    blue: "bg-blue-500",
    indigo: "bg-indigo-500",
    purple: "bg-purple-500",
    green: "bg-green-500",
    orange: "bg-orange-500",
    red: "bg-red-500",
  };

  const textColorClasses: Record<string, string> = {
    gray: "text-gray-500",
    blue: "text-blue-500",
    indigo: "text-indigo-500",
    purple: "text-purple-500",
    green: "text-green-500",
    orange: "text-orange-500",
    red: "text-red-500",
  };

  const sizeClasses: Record<string, string> = {
    xs: "w-1 h-1",
    sm: "w-1.5 h-1.5",
    md: "w-2 h-2",
    lg: "w-2.5 h-2.5",
  };

  const spinnerSizeClasses: Record<string, string> = {
    xs: "w-3 h-3",
    sm: "w-4 h-4",
    md: "w-5 h-5",
    lg: "w-6 h-6",
  };

  if (variant === "pulse") {
    return (
      <div className="flex items-center gap-2">
        <span
          className={`${sizeClasses[size]} ${colorClasses[color]} rounded-full animate-pulse`}
        />
        {label && <span className="text-xs text-gray-500">{label}</span>}
      </div>
    );
  }

  if (variant === "spinner") {
    return (
      <div className="flex items-center gap-2">
        <svg
          className={`animate-spin ${spinnerSizeClasses[size]} ${textColorClasses[color]}`}
          viewBox="0 0 24 24"
        >
          <circle
            className="opacity-25"
            cx="12"
            cy="12"
            r="10"
            stroke="currentColor"
            strokeWidth="3"
            fill="none"
          />
          <path
            className="opacity-75"
            fill="currentColor"
            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
          />
        </svg>
        {label && <span className="text-xs text-gray-500">{label}</span>}
      </div>
    );
  }

  return (
    <div className="flex items-center gap-2">
      <div className="flex items-center gap-0.5">
        {[0, 1, 2].map((i) => (
          <span
            key={i}
            className={`${sizeClasses[size]} ${colorClasses[color]} rounded-full animate-pulse`}
            style={{ animationDelay: `${i * 0.15}s` }}
          />
        ))}
      </div>
      {label && <span className="text-xs text-gray-500">{label}</span>}
    </div>
  );
}
