// packages/navi-app/src/lib/components/ModelSelector.svelte
<script lang="ts">
  type Model = {
    value: string;
    displayName: string;
    description: string;
  };

  let {
    models = [],
    selectedModel = $bindable(""),
    onSelect,
  }: {
    models: Model[];
    selectedModel: string;
    onSelect?: (model: string) => void;
  } = $props();

  let isOpen = $state(false);
  let containerRef: HTMLDivElement | undefined = $state();

  const currentModel = $derived(models.find(m => m.value === selectedModel));

  function handleSelect(value: string, e: MouseEvent) {
    e.stopPropagation();
    selectedModel = value;
    isOpen = false;
    onSelect?.(value);
  }

  function toggleDropdown(e: MouseEvent) {
    e.stopPropagation();
    isOpen = !isOpen;
  }

  function handleClickOutside(e: MouseEvent) {
    if (containerRef && !containerRef.contains(e.target as Node)) {
      isOpen = false;
    }
  }

  $effect(() => {
    if (isOpen) {
      // Use a small timeout to ensure the dropdown opens first
      const timeoutId = setTimeout(() => {
        document.addEventListener("click", handleClickOutside);
      }, 0);
      
      return () => {
        clearTimeout(timeoutId);
        document.removeEventListener("click", handleClickOutside);
      };
    }
  });
</script>

<div class="relative" bind:this={containerRef}>
  <button
    onclick={toggleDropdown}
    class="w-full flex items-center justify-between gap-2 px-2.5 py-1.5 bg-white border border-gray-200 rounded-lg text-left hover:border-gray-300 transition-colors group"
  >
    <div class="flex-1 min-w-0">
      <div class="text-[11px] font-medium text-gray-900 truncate">
        {currentModel?.displayName || "Select model"}
      </div>
    </div>
    <svg 
      class={`w-3.5 h-3.5 text-gray-400 transition-transform ${isOpen ? 'rotate-180' : ''}`}
      fill="none" 
      stroke="currentColor" 
      viewBox="0 0 24 24"
    >
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
    </svg>
  </button>

  {#if isOpen}
    <div class="absolute bottom-full left-0 right-0 mb-1 bg-white border border-gray-200 rounded-lg shadow-lg overflow-hidden z-50 max-h-64 overflow-y-auto">
      {#each models as model}
        <button
          onclick={(e) => handleSelect(model.value, e)}
          class={`w-full px-3 py-2 text-left hover:bg-gray-50 transition-colors border-b border-gray-100 last:border-0 ${selectedModel === model.value ? 'bg-gray-50' : ''}`}
        >
          <div class="flex items-center gap-2">
            {#if selectedModel === model.value}
              <svg class="w-3 h-3 text-emerald-500 shrink-0" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
              </svg>
            {:else}
              <div class="w-3 h-3 shrink-0"></div>
            {/if}
            <div class="flex-1 min-w-0">
              <div class="text-[11px] font-medium text-gray-900">{model.displayName}</div>
              {#if model.description}
                <div class="text-[10px] text-gray-500 truncate">{model.description}</div>
              {/if}
            </div>
          </div>
        </button>
      {/each}
      {#if models.length === 0}
        <div class="px-3 py-2 text-[11px] text-gray-400 italic">Loading models...</div>
      {/if}
    </div>
  {/if}
</div>

// packages/navi-remix/app/components/sidebar/ModelSelector.tsx
import { useEffect } from "react";
import { useSettingsStore } from "~/stores/settingsStore";
import { Dropdown, DropdownItem } from "~/components/ui/Dropdown";
import { api } from "~/lib/api";

export function ModelSelector() {
  const availableModels = useSettingsStore((state) => state.availableModels);
  const selectedModel = useSettingsStore((state) => state.selectedModel);
  const setAvailableModels = useSettingsStore((state) => state.setAvailableModels);
  const setSelectedModel = useSettingsStore((state) => state.setSelectedModel);

  useEffect(() => {
    async function loadModels() {
      if (availableModels.length === 0) {
        try {
          const models = await api.models.list();
          setAvailableModels(
            models.map((m) => ({
              id: m.value,
              name: m.displayName || m.value,
            }))
          );
        } catch (error) {
          console.error("Failed to load models:", error);
          // Set default models as fallback
          setAvailableModels([
            { id: "claude-sonnet-4-20250514", name: "Claude Sonnet 4" },
            { id: "claude-opus-4-20250514", name: "Claude Opus 4" },
            { id: "claude-3-5-sonnet-20241022", name: "Claude 3.5 Sonnet" },
          ]);
        }
      }
    }
    loadModels();
  }, [availableModels.length, setAvailableModels]);

  const currentModel = availableModels.find((m) => m.id === selectedModel);
  const displayName = currentModel?.name || selectedModel.split("-").slice(0, 3).join(" ");

  return (
    <Dropdown
      trigger={
        <button className="flex w-full items-center justify-between rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm text-gray-700 hover:border-gray-300 transition-colors">
          <span className="flex items-center gap-2">
            <svg
              className="h-4 w-4 text-purple-500"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
              />
            </svg>
            <span className="truncate">{displayName}</span>
          </span>
          <svg
            className="h-4 w-4 text-gray-400"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M19 9l-7 7-7-7"
            />
          </svg>
        </button>
      }
    >
      {availableModels.map((model) => (
        <DropdownItem
          key={model.id}
          onClick={() => setSelectedModel(model.id)}
          className={selectedModel === model.id ? "bg-gray-100" : ""}
        >
          <span className="flex items-center gap-2">
            {selectedModel === model.id && (
              <svg
                className="h-4 w-4 text-blue-600"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M5 13l4 4L19 7"
                />
              </svg>
            )}
            <span className={selectedModel !== model.id ? "pl-6" : ""}>
              {model.name}
            </span>
          </span>
        </DropdownItem>
      ))}
    </Dropdown>
  );
}
