// packages/navi-app/src/lib/components/SearchModal.svelte
<script lang="ts">
  import { api, type SearchResult } from "../api";

  let { isOpen = $bindable(false), projectId = null as string | null, onNavigate = (sessionId: string, projectId: string) => {}, onNavigateProject = (projectId: string) => {} } = $props();

  let searchQuery = $state("");
  let results = $state<SearchResult[]>([]);
  let isLoading = $state(false);
  let selectedIndex = $state(0);
  let inputRef: HTMLInputElement | null = $state(null);
  let debounceTimer: ReturnType<typeof setTimeout> | null = null;

  let groupedResults = $derived(() => {
    const projects = results.filter(r => r.entity_type === 'project');
    const sessions = results.filter(r => r.entity_type === 'session');
    const messages = results.filter(r => r.entity_type === 'message');
    return { projects, sessions, messages };
  });

  let flatResults = $derived(() => {
    const { projects, sessions, messages } = groupedResults();
    return [...projects, ...sessions, ...messages];
  });

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === "Escape") {
      e.stopPropagation();
      isOpen = false;
    } else if (e.key === "ArrowDown") {
      e.preventDefault();
      const flat = flatResults();
      selectedIndex = Math.min(selectedIndex + 1, flat.length - 1);
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      selectedIndex = Math.max(selectedIndex - 1, 0);
    } else if (e.key === "Enter") {
      e.preventDefault();
      const flat = flatResults();
      if (flat[selectedIndex]) {
        selectResult(flat[selectedIndex]);
      }
    }
  }

  async function performSearch(query: string) {
    if (!query.trim()) {
      results = [];
      return;
    }

    isLoading = true;
    try {
      results = await api.search.query(query, { projectId: projectId || undefined, limit: 30 });
      selectedIndex = 0;
    } catch (e) {
      console.error("Search failed:", e);
      results = [];
    } finally {
      isLoading = false;
    }
  }

  function handleInput(e: Event) {
    const value = (e.target as HTMLInputElement).value;
    searchQuery = value;
    
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => performSearch(value), 150);
  }

  function selectResult(result: SearchResult) {
    if (result.entity_type === 'project' && result.project_id) {
      onNavigateProject(result.project_id);
      isOpen = false;
    } else if (result.session_id && result.project_id) {
      onNavigate(result.session_id, result.project_id);
      isOpen = false;
    }
  }

  function formatTime(timestamp: number): string {
    const date = new Date(timestamp);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMins / 60);
    const diffDays = Math.floor(diffHours / 24);

    if (diffMins < 1) return "just now";
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    if (diffDays < 7) return `${diffDays}d ago`;
    return date.toLocaleDateString();
  }

  function highlightMatch(text: string, query: string): string {
    if (!query.trim() || !text) return text || "";
    const escapedTerms = query.toLowerCase().split(/\s+/).map(t => 
      t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    );
    let result = text;
    for (const term of escapedTerms) {
      if (term) {
        const regex = new RegExp(`(${term})`, "gi");
        result = result.replace(regex, '<mark class="bg-amber-100 text-amber-800 rounded px-0.5">$1</mark>');
      }
    }
    return result;
  }

  function getGlobalIndex(result: SearchResult): number {
    return flatResults().indexOf(result);
  }

  $effect(() => {
    if (isOpen && inputRef) {
      setTimeout(() => inputRef?.focus(), 50);
    }
  });

  $effect(() => {
    if (!isOpen) {
      searchQuery = "";
      results = [];
      selectedIndex = 0;
    }
  });
</script>

{#if isOpen}
  <div 
    class="fixed inset-0 bg-black/50 z-50 flex items-start justify-center pt-[12vh]"
    onclick={() => isOpen = false}
    onkeydown={handleKeydown}
    role="dialog"
    aria-modal="true"
  >
    <div 
      class="bg-white rounded-xl shadow-2xl w-full max-w-2xl border border-gray-200 overflow-hidden"
      onclick={(e) => e.stopPropagation()}
      role="presentation"
    >
      <div class="p-4 border-b border-gray-200">
        <div class="flex items-center gap-3">
          <svg class="w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
          <input
            bind:this={inputRef}
            type="text"
            value={searchQuery}
            oninput={handleInput}
            placeholder={projectId ? "Search in project..." : "Search projects and chats..."}
            class="flex-1 bg-transparent text-gray-900 text-lg outline-none placeholder-gray-400"
          />
          {#if isLoading}
            <div class="w-5 h-5 border-2 border-gray-300 border-t-gray-600 rounded-full animate-spin"></div>
          {:else if searchQuery}
            <button 
              onclick={() => { searchQuery = ""; results = []; }}
              class="text-gray-400 hover:text-gray-600"
            >
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          {/if}
        </div>
      </div>

      <div class="max-h-[55vh] overflow-y-auto">
        {#if results.length > 0}
          {@const grouped = groupedResults()}
          
          {#if grouped.projects.length > 0}
            <div class="px-4 py-2 bg-gray-50 border-b border-gray-100">
              <span class="text-xs font-semibold text-gray-500 uppercase tracking-wider">Projects</span>
            </div>
            {#each grouped.projects as result}
              {@const globalIdx = getGlobalIndex(result)}
              <button
                class="w-full text-left px-4 py-3 hover:bg-gray-50 flex items-start gap-3 border-b border-gray-100 transition-colors {selectedIndex === globalIdx ? 'bg-blue-50' : ''}"
                onclick={() => selectResult(result)}
                onmouseenter={() => selectedIndex = globalIdx}
              >
                <span class="text-lg mt-0.5">📁</span>
                <div class="flex-1 min-w-0">
                  <div class="flex items-center gap-2">
                    <span class="text-gray-900 font-medium">
                      {@html highlightMatch(result.preview || result.project_name || "Untitled", searchQuery)}
                    </span>
                    <span class="text-xs text-gray-400">{formatTime(result.updated_at)}</span>
                  </div>
                </div>
              </button>
            {/each}
          {/if}

          {#if grouped.sessions.length > 0}
            <div class="px-4 py-2 bg-gray-50 border-b border-gray-100">
              <span class="text-xs font-semibold text-gray-500 uppercase tracking-wider">Chats</span>
            </div>
            {#each grouped.sessions as result}
              {@const globalIdx = getGlobalIndex(result)}
              <button
                class="w-full text-left px-4 py-3 hover:bg-gray-50 flex items-start gap-3 border-b border-gray-100 transition-colors {selectedIndex === globalIdx ? 'bg-blue-50' : ''}"
                onclick={() => selectResult(result)}
                onmouseenter={() => selectedIndex = globalIdx}
              >
                <span class="text-lg mt-0.5">💬</span>
                <div class="flex-1 min-w-0">
                  <div class="flex items-center gap-2">
                    <span class="text-gray-900 font-medium truncate">
                      {@html highlightMatch(result.session_title || "Untitled", searchQuery)}
                    </span>
                    <span class="text-xs text-gray-400">{formatTime(result.updated_at)}</span>
                  </div>
                  {#if result.project_name}
                    <span class="text-xs text-gray-400 mt-0.5 inline-block">
                      {@html highlightMatch(result.project_name, searchQuery)}
                    </span>
                  {/if}
                </div>
              </button>
            {/each}
          {/if}

          {#if grouped.messages.length > 0}
            <div class="px-4 py-2 bg-gray-50 border-b border-gray-100">
              <span class="text-xs font-semibold text-gray-500 uppercase tracking-wider">Messages</span>
            </div>
            {#each grouped.messages as result}
              {@const globalIdx = getGlobalIndex(result)}
              <button
                class="w-full text-left px-4 py-3 hover:bg-gray-50 flex items-start gap-3 border-b border-gray-100 transition-colors {selectedIndex === globalIdx ? 'bg-blue-50' : ''}"
                onclick={() => selectResult(result)}
                onmouseenter={() => selectedIndex = globalIdx}
              >
                <span class="text-lg mt-0.5">📝</span>
                <div class="flex-1 min-w-0">
                  <div class="flex items-center gap-2">
                    <span class="text-gray-700 font-medium truncate">{result.session_title || "Untitled"}</span>
                    <span class="text-xs text-gray-400">{formatTime(result.updated_at)}</span>
                  </div>
                  {#if result.preview}
                    <p class="text-sm text-gray-500 truncate mt-0.5">
                      {@html highlightMatch(result.preview.slice(0, 120), searchQuery)}
                    </p>
                  {/if}
                  {#if result.project_name}
                    <span class="text-xs text-gray-400 mt-0.5 inline-block">{result.project_name}</span>
                  {/if}
                </div>
              </button>
            {/each}
          {/if}
        {:else if searchQuery && !isLoading}
          <div class="px-4 py-8 text-center text-gray-500">
            No results found for "{searchQuery}"
          </div>
        {:else if !searchQuery}
          <div class="px-4 py-8 text-center text-gray-400">
            <p class="text-sm">Start typing to search your projects and chats</p>
            <p class="text-xs mt-2 text-gray-400">Tip: Use Cmd+K to open search anytime</p>
          </div>
        {/if}
      </div>

      <div class="px-4 py-2 border-t border-gray-200 flex items-center justify-between text-xs text-gray-500">
        <div class="flex gap-4">
          <span><kbd class="bg-gray-100 px-1.5 py-0.5 rounded text-gray-600">↑↓</kbd> navigate</span>
          <span><kbd class="bg-gray-100 px-1.5 py-0.5 rounded text-gray-600">↵</kbd> select</span>
          <span><kbd class="bg-gray-100 px-1.5 py-0.5 rounded text-gray-600">esc</kbd> close</span>
        </div>
        {#if results.length > 0}
          <span>{results.length} result{results.length !== 1 ? 's' : ''}</span>
        {/if}
      </div>
    </div>
  </div>
{/if}

// packages/navi-remix/app/components/search/SearchModal.tsx
import { useState, useEffect, useRef, useCallback } from "react";
import { useProjectStore } from "~/stores/projectStore";
import { useSessionStore } from "~/stores/sessionStore";

interface SearchModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectProject: (projectId: string) => void;
  onSelectSession: (projectId: string, sessionId: string) => void;
}

interface SearchResult {
  type: "project" | "session";
  id: string;
  projectId?: string;
  title: string;
  subtitle?: string;
}

export function SearchModal({
  isOpen,
  onClose,
  onSelectProject,
  onSelectSession,
}: SearchModalProps) {
  const [query, setQuery] = useState("");
  const [selectedIndex, setSelectedIndex] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);

  const projects = useProjectStore((s) => s.projects);
  const sessions = useSessionStore((s) => s.sessions);

  // Build search results
  const results: SearchResult[] = [];

  // Add matching projects
  projects
    .filter((p) => !p.archived)
    .forEach((project) => {
      if (
        !query ||
        project.name.toLowerCase().includes(query.toLowerCase()) ||
        project.path.toLowerCase().includes(query.toLowerCase())
      ) {
        results.push({
          type: "project",
          id: project.id,
          title: project.name,
          subtitle: project.path,
        });
      }

      // Add matching sessions for this project
      const projectSessions = sessions.get(project.id) || [];
      projectSessions
        .filter((s) => !s.archived)
        .forEach((session) => {
          if (
            !query ||
            session.title?.toLowerCase().includes(query.toLowerCase())
          ) {
            results.push({
              type: "session",
              id: session.id,
              projectId: project.id,
              title: session.title || "Untitled",
              subtitle: project.name,
            });
          }
        });
    });

  // Focus input when modal opens
  useEffect(() => {
    if (isOpen) {
      setQuery("");
      setSelectedIndex(0);
      setTimeout(() => inputRef.current?.focus(), 50);
    }
  }, [isOpen]);

  // Keyboard navigation
  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === "ArrowDown") {
        e.preventDefault();
        setSelectedIndex((i) => Math.min(i + 1, results.length - 1));
      } else if (e.key === "ArrowUp") {
        e.preventDefault();
        setSelectedIndex((i) => Math.max(i - 1, 0));
      } else if (e.key === "Enter") {
        e.preventDefault();
        const selected = results[selectedIndex];
        if (selected) {
          if (selected.type === "project") {
            onSelectProject(selected.id);
          } else {
            onSelectSession(selected.projectId!, selected.id);
          }
          onClose();
        }
      } else if (e.key === "Escape") {
        onClose();
      }
    },
    [results, selectedIndex, onSelectProject, onSelectSession, onClose]
  );

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center pt-[20vh]">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/30" onClick={onClose} />

      {/* Modal */}
      <div className="relative w-full max-w-lg bg-white rounded-xl shadow-2xl overflow-hidden">
        {/* Search input */}
        <div className="flex items-center gap-3 px-4 py-3 border-b border-gray-200">
          <svg
            className="w-5 h-5 text-gray-400"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
            />
          </svg>
          <input
            ref={inputRef}
            type="text"
            value={query}
            onChange={(e) => {
              setQuery(e.target.value);
              setSelectedIndex(0);
            }}
            onKeyDown={handleKeyDown}
            placeholder="Search projects and chats..."
            className="flex-1 text-sm text-gray-900 placeholder-gray-400 outline-none"
          />
          <kbd className="px-2 py-0.5 text-xs text-gray-400 bg-gray-100 rounded">
            ESC
          </kbd>
        </div>

        {/* Results */}
        <div className="max-h-80 overflow-y-auto py-2">
          {results.length === 0 ? (
            <div className="px-4 py-8 text-center text-sm text-gray-500">
              No results found
            </div>
          ) : (
            results.map((result, i) => (
              <button
                key={`${result.type}-${result.id}`}
                onClick={() => {
                  if (result.type === "project") {
                    onSelectProject(result.id);
                  } else {
                    onSelectSession(result.projectId!, result.id);
                  }
                  onClose();
                }}
                className={`w-full flex items-center gap-3 px-4 py-2 text-left transition-colors ${
                  i === selectedIndex ? "bg-gray-100" : "hover:bg-gray-50"
                }`}
              >
                {result.type === "project" ? (
                  <svg
                    className="w-5 h-5 text-blue-500"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"
                    />
                  </svg>
                ) : (
                  <svg
                    className="w-5 h-5 text-gray-400"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"
                    />
                  </svg>
                )}
                <div className="flex-1 min-w-0">
                  <div className="text-sm font-medium text-gray-900 truncate">
                    {result.title}
                  </div>
                  {result.subtitle && (
                    <div className="text-xs text-gray-500 truncate">
                      {result.subtitle}
                    </div>
                  )}
                </div>
                <span className="text-xs text-gray-400">
                  {result.type === "project" ? "Project" : "Chat"}
                </span>
              </button>
            ))
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center gap-4 px-4 py-2 border-t border-gray-200 bg-gray-50 text-xs text-gray-500">
          <span className="flex items-center gap-1">
            <kbd className="px-1.5 py-0.5 bg-white border border-gray-200 rounded">↑</kbd>
            <kbd className="px-1.5 py-0.5 bg-white border border-gray-200 rounded">↓</kbd>
            to navigate
          </span>
          <span className="flex items-center gap-1">
            <kbd className="px-1.5 py-0.5 bg-white border border-gray-200 rounded">↵</kbd>
            to select
          </span>
        </div>
      </div>
    </div>
  );
}
