// packages/navi-remix/app/components/chat/StreamingPreview.tsx
import { useMemo } from "react";
import type {
  ContentBlock,
  TextBlock,
  ThinkingBlock,
  ToolUseBlock,
} from "~/lib/claude";
import { WorkingIndicator } from "./WorkingIndicator";
import { MermaidRenderer } from "./MermaidRenderer";

interface StreamingPreviewProps {
  blocks: ContentBlock[];
  partialText: string;
  partialThinking?: string;
  renderMarkdown: (content: string) => string;
  jsonBlocksMap?: Map<string, any>;
}

interface DisplayBlock {
  block: ContentBlock;
  isStreaming: boolean;
  streamingContent?: string;
}

const toolIcons: Record<string, string> = {
  Read: "📄",
  Write: "✏️",
  Edit: "🔧",
  MultiEdit: "🔧",
  Bash: "⚡",
  Glob: "🔍",
  Grep: "🔎",
  WebFetch: "🌐",
  WebSearch: "🔍",
};

export function StreamingPreview({
  blocks,
  partialText,
  partialThinking = "",
  renderMarkdown,
  jsonBlocksMap = new Map(),
}: StreamingPreviewProps) {
  const displayBlocks = useMemo((): DisplayBlock[] => {
    return blocks.map((block, idx) => {
      const isLast = idx === blocks.length - 1;
      if (isLast) {
        if (block.type === "text") {
          return {
            block,
            isStreaming: true,
            streamingContent: partialText || (block as TextBlock).text,
          };
        }
        if (block.type === "thinking") {
          return {
            block,
            isStreaming: true,
            streamingContent: partialThinking || (block as ThinkingBlock).thinking,
          };
        }
        if (block.type === "tool_use") {
          return { block, isStreaming: true };
        }
      }
      return { block, isStreaming: false };
    });
  }, [blocks, partialText, partialThinking]);

  return (
    <div className="flex gap-4 w-full pr-4 md:pr-0 animate-in fade-in duration-150">
      <div className="w-8 h-8 rounded-lg bg-white border border-gray-200 flex-shrink-0 flex items-center justify-center shadow-sm">
        <WorkingIndicator variant="spinner" size="md" color="gray" />
      </div>

      <div className="flex-1 min-w-0 space-y-3">
        {displayBlocks.map(({ block, isStreaming, streamingContent }, idx) => (
          <div key={idx} className="animate-in fade-in slide-in-from-bottom-1 duration-200">
            {block.type === "text" && (
              <div className="text-[15px] leading-7 text-gray-800 markdown-body">
                <MermaidRenderer
                  content={streamingContent || (block as TextBlock).text || ""}
                  renderMarkdown={renderMarkdown}
                  jsonBlocksMap={jsonBlocksMap}
                />
                {isStreaming && (
                  <span className="inline-block w-0.5 h-5 bg-blue-500 ml-0.5 align-middle animate-pulse" />
                )}
              </div>
            )}

            {block.type === "thinking" && (
              <div className="rounded-xl border border-purple-200 bg-purple-50/30 shadow-sm p-4 transition-all duration-200">
                <div className="flex items-center gap-3 mb-2">
                  <div className="w-7 h-7 rounded-lg bg-purple-100 flex items-center justify-center flex-shrink-0">
                    <span className="text-sm">💭</span>
                  </div>
                  <span className="text-sm font-medium text-purple-800">
                    Thinking
                  </span>
                  <WorkingIndicator variant="dots" size="xs" color="purple" />
                </div>
                <pre className="text-xs text-purple-700 whitespace-pre-wrap font-mono max-h-32 overflow-y-auto pl-10">
                  {streamingContent || (block as ThinkingBlock).thinking || ""}
                </pre>
              </div>
            )}

            {block.type === "tool_use" && (
              <div className="rounded-xl border border-gray-200 bg-white shadow-sm p-4 transition-all duration-200">
                <div className="flex items-center gap-3">
                  <div className="w-7 h-7 rounded-lg bg-gray-100 flex items-center justify-center flex-shrink-0">
                    <span className="text-sm">
                      {toolIcons[(block as ToolUseBlock).name] || "⚙️"}
                    </span>
                  </div>
                  <span className="text-sm font-medium text-gray-900">
                    {(block as ToolUseBlock).name}
                  </span>
                  <WorkingIndicator variant="dots" size="xs" color="gray" />
                </div>
              </div>
            )}
          </div>
        ))}

        {blocks.length === 0 && (
          <div className="h-8 flex items-center">
            <WorkingIndicator
              variant="dots"
              size="xs"
              color="gray"
              label="Thinking..."
            />
          </div>
        )}
      </div>
    </div>
  );
}

// packages/navi-app/src/lib/components/StreamingPreview.svelte
<script lang="ts">
  import type { ContentBlock, ToolUseBlock, TextBlock, ThinkingBlock } from "../claude";
  import MermaidRenderer from "./MermaidRenderer.svelte";
  import WorkingIndicator from "./WorkingIndicator.svelte";
  import { fade } from "svelte/transition";

  interface Props {
    blocks: ContentBlock[];
    partialText: string;
    partialThinking: string;
    renderMarkdown: (content: string) => string;
    jsonBlocksMap?: Map<string, any>;
    shellBlocksMap?: Map<string, { code: string; language: string }>;
    onRunInTerminal?: (command: string) => void;
  }

  let { blocks, partialText, partialThinking, renderMarkdown, jsonBlocksMap = new Map(), shellBlocksMap = new Map(), onRunInTerminal }: Props = $props();

  function getDisplayBlocks(): { block: ContentBlock; isStreaming: boolean; streamingContent?: string }[] {
    return blocks.map((block, idx) => {
      const isLast = idx === blocks.length - 1;
      if (isLast) {
        if (block.type === "text") {
          return { block, isStreaming: true, streamingContent: partialText || (block as TextBlock).text };
        }
        if (block.type === "thinking") {
          return { block, isStreaming: true, streamingContent: partialThinking || (block as ThinkingBlock).thinking };
        }
        if (block.type === "tool_use") {
          return { block, isStreaming: true };
        }
      }
      return { block, isStreaming: false };
    });
  }

  function getToolSummary(tool: ToolUseBlock): string {
    const input = tool.input || {};
    switch (tool.name) {
      case "Read":
        return input.file_path?.split("/").pop() || "";
      case "Write":
        return input.file_path?.split("/").pop() || "";
      case "Edit":
      case "MultiEdit":
        return input.file_path?.split("/").pop() || "";
      case "Bash":
        const cmd = input.command || "";
        return cmd.length > 40 ? cmd.slice(0, 40) + "..." : cmd;
      case "Glob":
        return input.pattern || "";
      case "Grep":
        return input.pattern || "";
      case "WebFetch":
        try { return new URL(input.url || "").hostname; } catch { return ""; }
      case "WebSearch":
        return input.query || "";
      case "TodoWrite":
        return `${input.todos?.length || 0} items`;
      default:
        return "";
    }
  }
</script>

<style>
  .streaming-text {
    transition: opacity 0.15s ease-out;
  }

  .cursor {
    animation: blink 1s ease-in-out infinite;
  }

  @keyframes blink {
    0%, 50% { opacity: 1; }
    51%, 100% { opacity: 0; }
  }

  .fade-in {
    animation: fadeIn 0.2s ease-out;
  }

  @keyframes fadeIn {
    from { opacity: 0; transform: translateY(4px); }
    to { opacity: 1; transform: translateY(0); }
  }
</style>

<div class="w-full" in:fade={{ duration: 150 }}>
  <div class="space-y-2">
    {#each getDisplayBlocks() as { block, isStreaming, streamingContent }, idx (idx)}
      <div class="fade-in">
        {#if block.type === "text"}
          <div class="text-sm leading-relaxed text-gray-800 markdown-body streaming-text">
            <MermaidRenderer content={streamingContent || (block as TextBlock).text || ""} {renderMarkdown} {jsonBlocksMap} {shellBlocksMap} {onRunInTerminal} />
            {#if isStreaming}
              <span class="cursor inline-block w-0.5 h-4 bg-blue-500 ml-0.5 align-middle"></span>
            {/if}
          </div>
        {:else if block.type === "thinking"}
          <div class="flex items-center gap-1.5 py-0.5 max-w-full text-xs text-gray-400 dark:text-gray-500">
            <span class="shrink-0 font-medium animate-pulse">Thinking</span>
            {#if (streamingContent || "").trim()}
              <span class="truncate text-gray-300 dark:text-gray-600">· {(streamingContent || "").trim().slice(-80)}</span>
            {/if}
          </div>
        {:else if block.type === "tool_use"}
          {@const tool = block as ToolUseBlock}
          {@const summary = getToolSummary(tool)}
          <div class="rounded-lg border border-blue-200 bg-blue-50/30 overflow-hidden transition-colors">
            <div class="flex items-center gap-2 px-3 py-2">
              <div class="w-6 h-6 rounded-md bg-blue-100 flex items-center justify-center flex-shrink-0">
                <svg class="w-3.5 h-3.5 text-blue-500 animate-spin" fill="none" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="3"></circle>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
              </div>
              <span class="text-xs font-medium text-blue-700">{tool.name}</span>
              {#if summary}
                <span class="text-xs text-blue-400 truncate font-mono flex-1">{summary}</span>
              {/if}
              <span class="text-xs text-blue-500 shrink-0">Running...</span>
            </div>
          </div>
        {/if}
      </div>
    {/each}

    {#if blocks.length === 0}
      <div class="h-6 flex items-center">
        <WorkingIndicator variant="dots" size="xs" color="gray" label="Thinking..." />
      </div>
    {/if}
  </div>
</div>
