// packages/navi-remix/app/components/chat/TodoProgress.tsx
import type { Todo } from "~/lib/types";

interface TodoProgressProps {
  todos: Todo[];
  showWhenEmpty?: boolean;
}

export function TodoProgress({ todos, showWhenEmpty = false }: TodoProgressProps) {
  if (todos.length === 0 && !showWhenEmpty) return null;

  const completed = todos.filter((t) => t.status === "completed").length;
  const inProgress = todos.filter((t) => t.status === "in_progress");
  const pending = todos.filter((t) => t.status === "pending").length;
  const total = todos.length;
  const progress = total > 0 ? (completed / total) * 100 : 0;

  return (
    <div className="rounded-lg border border-gray-200 bg-white p-3 space-y-2">
      {/* Header with progress */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <svg
            className="w-4 h-4 text-gray-500"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"
            />
          </svg>
          <span className="text-xs font-medium text-gray-700">
            Tasks ({completed}/{total})
          </span>
        </div>
        <span className="text-xs text-gray-500">{Math.round(progress)}%</span>
      </div>

      {/* Progress bar */}
      <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
        <div
          className="h-full bg-green-500 rounded-full transition-all duration-300"
          style={{ width: `${progress}%` }}
        />
      </div>

      {/* Current task */}
      {inProgress.length > 0 && (
        <div className="flex items-center gap-2 text-xs text-blue-600">
          <svg className="w-3 h-3 animate-spin" viewBox="0 0 24 24">
            <circle
              className="opacity-25"
              cx="12"
              cy="12"
              r="10"
              stroke="currentColor"
              strokeWidth="3"
              fill="none"
            />
            <path
              className="opacity-75"
              fill="currentColor"
              d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
            />
          </svg>
          <span>{inProgress[0].content}</span>
        </div>
      )}

      {/* Pending count */}
      {pending > 0 && inProgress.length === 0 && (
        <div className="text-xs text-gray-500">
          {pending} task{pending !== 1 ? "s" : ""} remaining
        </div>
      )}
    </div>
  );
}

// packages/navi-app/src/lib/components/TodoProgress.svelte
<script lang="ts">
  import type { TodoItem } from "../stores";
  import WorkingIndicator from "./WorkingIndicator.svelte";

  interface Props {
    todos: TodoItem[];
    showWhenEmpty?: boolean;
  }

  let { todos, showWhenEmpty = false }: Props = $props();

  const completedCount = $derived(todos.filter(t => t.status === "completed").length);
  const hasInProgress = $derived(todos.some(t => t.status === "in_progress"));
  
  // Only show if there are todos OR if showWhenEmpty is true
  const shouldShow = $derived(todos.length > 0 || showWhenEmpty);
</script>

{#if shouldShow}
  <div class="flex gap-4 w-full">
    <div class="w-8 h-8 rounded-lg bg-white border border-gray-200 flex-shrink-0 flex items-center justify-center shadow-sm">
      <WorkingIndicator variant="pulse" size="sm" color="gray" />
    </div>
    <div class="flex-1">
      {#if todos.length > 0}
        <div class="bg-gray-50 border border-gray-200 rounded-lg p-3">
          <div class="flex items-center gap-2 mb-2">
            <svg class="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"></path>
            </svg>
            <span class="text-xs font-medium text-gray-600">{completedCount}/{todos.length}</span>
          </div>
          <div class="space-y-1.5 max-h-32 overflow-y-auto">
            {#each todos as todo}
              <div class="flex items-start gap-2">
                <div class="mt-0.5 shrink-0">
                  {#if todo.status === "completed"}
                    <div class="w-4 h-4 rounded-full bg-green-100 flex items-center justify-center">
                      <svg class="w-2.5 h-2.5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                      </svg>
                    </div>
                  {:else if todo.status === "in_progress"}
                    <WorkingIndicator variant="spin" size="lg" color="gray" />
                  {:else}
                    <div class="w-4 h-4 rounded-full border-2 border-gray-300"></div>
                  {/if}
                </div>
                <span class={`text-xs ${todo.status === "completed" ? "text-gray-400 line-through" : todo.status === "in_progress" ? "text-gray-900 font-medium" : "text-gray-600"}`}>
                  {todo.status === "in_progress" && todo.activeForm ? todo.activeForm + "..." : todo.content}
                </span>
              </div>
            {/each}
          </div>
        </div>
      {:else}
        <WorkingIndicator variant="dots" size="xs" color="gray" class="pt-2" />
      {/if}
    </div>
  </div>
{/if}
